### ISSUE TITLE
Rocket calculations

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#12]
@chrisnorth I've made a page to test the rocket calculations at http://chrisnorth.github.io/classroom-rocket-scientist/rocketeq Can you let me know if the results seem to be correct?

**Comment by slowe** [comment]
(This test doesn't include an actual payload which, I assume, would be added to the mass of the payload bay).

**Comment by chrisnorth** [comment]
Made a few minor changes - just including the dry mass in the final mass of each stage. Now it agrees with my calculations.

**Comment by slowe** [comment]
For the thrust-o-meter, should I use the deltaV as a fraction of the required deltaV for the selected orbit?
P.S. Thanks for fixing it Chris.

**Comment by chrisnorth** [comment]
Yes, I think a "percentage" bar is easiest and simplest - we don't care
about the absolute deltaV in display terms.
