### ISSUE TITLE
Automate generation of icons

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#15]
We'll create them as svg and the regenerate script should produce the png versions.

**Comment by chrisnorth** [comment]
I assume this will overwrite the existing PNG files (which I've made a few using Inkscape export to PNG).

Should we put the source SVG files somewhere else (e.g. in images/svg?) rather than just in /images

**Comment by chrisnorth** [comment]
SVG files are now in images/svg

**Comment by slowe** [comment]
Put source SVG files in `images/svg/`. The regenerate script will convert each svg in that directory and put it in `images/png/`. You'll need ImageMagick with RSVG enabled. The script should complain at you if you don't have it.
