### ISSUE TITLE
Remove 'undefined' requirement label

### ISSUE THREAD

**Issue by TheTrashFactory** [chrisnorth/classroom-rocket-scientist#17]
Remove 'undefined' requirement label when not provided for an instrument, e.g. Radar dish req. label removed from Beginners as it was duplicated by Radar altimeter req. label.

**Comment by slowe** [comment]
@TheTrashFactory Whereabouts does the "undefined" show up? I can't find it.

**Comment by TheTrashFactory** [comment]
@slowe You can see it on beginner scenarios that require a radar altimeter, so EO natural disaster and NAV map.

**Comment by slowe** [comment]
@TheTrashFactory Thanks! Having a look it now.
