### ISSUE TITLE
Discussion points

### ISSUE THREAD

**Issue by TheTrashFactory** [chrisnorth/classroom-rocket-scientist#19]
- make boxes standard size. 
- should deployable solar panels be available from small satellites?
- Label 'thrust bar'. Perhaps information (i) option to explain what this is and what is means when it goes over 100%. Some users might think this means the mission will fail.
- Add information about body sections. How many are needed, which ones, etc.

**Comment by slowe** [comment]
@TheTrashFactory Which boxes need to be a standard size?

We probably could label the thrust bar somehow. I'll add a ✕/✓ indicator 'light' that turns on at 100%. Does that help? 

The information about body sections could be added to the intro text for the section at the top.

**Comment by TheTrashFactory** [comment]
Point 1. refers to mission purpose boxes, e.g....
<img width="1265" alt="boxes" src="https://cloud.githubusercontent.com/assets/11634784/19267403/64ba9186-8fa6-11e6-901f-0263766180e7.png">

**Comment by slowe** [comment]
Deployable solar panels are now available for small satellites.

**Comment by slowe** [comment]
![screen shot 2016-10-11 at 14 29 34](https://cloud.githubusercontent.com/assets/299787/19272127/45875e16-8fbf-11e6-99f0-106e092f30cf.png)
![screen shot 2016-10-11 at 14 35 43](https://cloud.githubusercontent.com/assets/299787/19272315/09a946ec-8fc0-11e6-96dd-f642af9ce948.png)
- [x] make boxes standard size.
- [x] deployable solar panels available for small satellites
- [x] help user understand that thrust bar over 100% isn't a fail
- [ ] add information about body sections. How many are needed, which ones, etc.
- [ ] Sarah to check beginner
- [ ] Chris to check advanced
