### ISSUE TITLE
Boosters

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#2]
Add boosters. Can have 0, 2, 4, or 6.

**Comment by slowe** [comment]
Where do the boosters fit into the rocket equation? Do they just add to stage 1? Happen before/after stage 1?

**Comment by chrisnorth** [comment]
I would just add them on to stage 1 in terms of masses and impulses. If we
need to assume they fire for the same duration as stage 1 that's fine -
close enough, at least!

**Comment by chrisnorth** [comment]
Boosters now no longer required
