### ISSUE TITLE
Power requirements are too high compared with solar panel provision

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/classroom-rocket-scientist#21]
Power requirements (inc. main bus power) are too high compared with how much solar panels provide

**Comment by slowe** [comment]
This seems to be an issue for the cube sat in advanced mode. It currently seems to require 100W.

**Comment by chrisnorth** [comment]
@TheTrashFactory There shouldn't be any effect on beginner, since solar panels have infinite power.

Since cubesats have a maximum power supply of 15W (from body-mounted solar panels) the power supply has to be around 5W (to allow space for instruments)

**Comment by slowe** [comment]
Are these power requirements sorted now? Does it matter that the "camera (miniature)" uses up the entire power budget (because the bus uses 5W)?

**Comment by chrisnorth** [comment]
I've not sorted them yet - it's on my list for this week...

+----------------------------------------------------------+
| Dr Chris North
| -
| Ogden Science Lecturer
| STFC Public Engagement Fellow
| Undergraduate Admissions Tutor
| -
| School of Physics and Astronomy, Cardiff University
| chris.north@astro.cf.ac.uk
| +44 (0)29 208 70537
+----------------------------------------------------------+
