### ISSUE TITLE
Instrument/power package icons

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#3]
Add icons. Use 32x32 textures.

**Comment by chrisnorth** [comment]
I've started adding a couple of icons @slowe - did you intend them to be added through CSS (I've added to style.scss, and images/icon-time.png).

I did add some code to the processPackage function to add an img tag for something with a "file" key in the "texture" of the package - which is another option.

**Comment by chrisnorth** [comment]
@slowe  I've also not figured out how to deal with the fact that some textures are rotated - so I've had to add icon-camera-wide.png and icon-camera-tall.png, and associated css for "up" and "down" slots. I'm not sure of the best way to rotate a background image (if there is one)...

**Comment by chrisnorth** [comment]
These should be SVG images

**Comment by slowe** [comment]
@chrisnorth Yes, at the moment they are added through CSS. I've removed the need to create a separate, rotated, image for the 2x4 packages.

**Comment by slowe** [comment]
Dish for cubesat is broken. I need to fix this.

**Comment by slowe** [comment]
The textures for icons can be added in `style.scss`. The foil textures I've added through `tests\satellite\satellite.scss` so that the styles don't over-ride styles within that file.
