### ISSUE TITLE
Show thrust meter

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#4]
Use the appropriate equations to display the thrust. Normalised to the required thrust.

**Comment by slowe** [comment]
@chrisnorth (I mistakenly asked this question on issue #12 but this is a more appropriate place). Should I use the ratio of deltaV from the chosen rocket to deltaV required for the orbit as we don't calculate the required thrust?

**Comment by chrisnorth** [comment]
Yes, I think deltaV is a suitable proxy for thrust.
