### ISSUE TITLE
Ready to launch screen

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#6]
The text needs to be updated as appropriate to show outstanding issues.

**Comment by chrisnorth** [comment]
- [x] Beginner: list all problems
- [x] Intermediate: list sections where there are problems
- [x] Advanced: say there are problems

**Comment by chrisnorth** [comment]
Also: in Beginner add text to say "Now try again in Intermediate", and similarly for Intermediate->Advanced

**Comment by slowe** [comment]
Now that the launch is separated from the "ready to launch" screen, the "Now try again in intermediate" link should be on the separate launch page. This link should be added to the launch screen in #7

**Comment by slowe** [comment]
@chrisnorth You can change the text displayed on the `Ready to launch?` screen for each level as appropriate by changing `launch.prep.checklist` and `launch.prep.goforlaunch` (special options are `$requirementslist$` and `$requirementssectionlist$` which will show the requirement errors (you wanted this for beginner) or the sections where there are outstanding requirements (you wanted that for intermediate). You can set a requirement for a stable rocket (not wobbly) and suitably constructed (the power bar reaches 100%). For beginner I've just required that it be constructed and not required that it be stable. Feel free to change that.

Note that all requirements have a `label` (shown in the `Requirements` box as you go through) and an `error` that shows up on the `Ready to launch?` screen. If there is no `label` attribute they don't show up.
