### ISSUE TITLE
Launch (probably postponed)

### ISSUE THREAD

**Issue by slowe** [chrisnorth/classroom-rocket-scientist#7]
The animation dealing with the launch needs to be created.

**Comment by slowe** [comment]
Add UK Space Agency logo (and ESA) to rocket

**Comment by chrisnorth** [comment]
Text needed for:
- [ ] Welcome to the launch of the UK Space Agency's latest %mission% satellite to %aims%
- [ ] Count down
- [ ] Lift off! / Launch
- [ ] Stage [1-3] ignition
- [ ] Stage [1-3] fuel exhausted (time & speed calculated)
- [ ] Stage [1-3] separation (after stage fuel exhausted or orbit achieved)
- [ ] Mission elapsed time: T+<>
- [ ] Current speed:
- [ ] %orbit% achieved (after final stage finished)
- [ ] Payload bay opened (after a few seconds)
- [ ] Satellite deployed (after a few seconds)
- [ ] Deploying solar panels (after a few seconds)
- [ ] Solar panels deployed (after 4 seconds (1 per solar panel)?)
- [ ] Satellite operational (after 3 seconds)
- [ ] Success message (per scenario) e.g. "Congratulations, your %mission% satellite is now %aims% on behalf of the UK Space Agency"

Messages timed correctly for real situation - with "skip to next" button.

**Comment by chrisnorth** [comment]
Implemented with constant (1s) pauses, and no skip button. Closing issue.
